[package]
name = "golden-axe-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio             = { version = "1.3", features = ["rt-multi-thread", "macros"] }
teloxide          = { version = "0.5", features = ["auto-send", "macros", "rustls"] }
log               = "0.4"
pretty_env_logger = "0.4.0"
anyhow            = "1.0.51"
dotenv            = "0.15.0"
mod_use           = "0.2.0"
if_chain          = "1.0.2"
url               = "2.2.2"
tokio-stream      = "0.1.8"
axum              = "0.4.2"

[[bin]]
name = "golden-axe"
path = "src/main.rs"
