# fly.toml file generated for golden-axe on 2021-12-09T22:54:59+08:00

app = "golden-axe"

kill_signal  = "SIGINT"
kill_timeout = 5
processes    = []

[env]
DOMAIN = "golden-axe.fly.dev"
ENV    = "Production"

[[services]]
internal_port = 8080
protocol      = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type       = "connections"

[[services.ports]]
handlers = ["http"]
port     = 80

[[services.ports]]
handlers = ["tls", "http"]
port     = 443

[[services.http_checks]]
path            = "/health"
method          = "get"
timeout         = 2000
interval        = 10000
protocol        = "http"
grace_period    = "5s"
tls_skip_verify = false
